package constants;

public enum RequestCode {
    LOGIN_REQUEST,
    SIGNUP_REQUEST,
    SET_STATUS,
    GET_SONGLIST,
    GET_SONG,
    HISTORY_REQUEST,
    GET_PLAYLISTS,
    CREATE_PLAYLIST,
    NEW_SONGS,
    SEARCH_SONG,
    CREATE_GROUP,
    ADD_SONG_TO_PLAYLIST,
    RECOMMENDATION,
    TRENDING,
    SYNCHRONIZATION,
    SEND_FEEDBACK,
    GET_FEEDBACK,
    USER_SEARCH,
    GET_STATUS,
    UPDATE_REQUEST,
    LOGOUT_REQUEST, 
    GET_PLAYLIST_SONGS,
    SHARE_PLAYLIST_REQUEST,
    GET_GROUPS_REQUEST, 
    GET_GROUP_PLAYLIST_REQUEST,
    CREATE_GROUP_PLAYLIST,
    DOWNLOAD_SONG_REQUEST;
    
    RequestCode(){
        this.toString();
    }
}
